version: '3.7'
services:
    SQL2019:
        image: sqldbawithabeard/dbachecksdemo
        ports:  
          - "15592:1433"
          - "5022:5022"          
        networks: 
          - BeardsMagicNetwork
        volumes: 
          - C:\Users\mrrob\Documents\dbatoolsdemo:/var/opt/mssql/backups
        environment:
          - MSSQL_ENABLE_HADR=1          
    SQL2019-1:
        image: sqldbawithabeard/dbachecksdemo
        ports:  
          - "15593:1433"
          - "5023:5023"         
        networks: 
          - BeardsMagicNetwork
        volumes: 
          - C:\Users\mrrob\Documents\dbatoolsdemo:/var/opt/mssql/backups
        environment:
          - MSSQL_ENABLE_HADR=1
networks: 
  BeardsMagicNetwork:
